{
 "title": "Dashboard Padrão",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Temperatura",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._field == \"temp\"\n  )"
    }
   ]
  },
  {
   "title": "Umidade",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._field == \"hum\"\n  )"
    }
   ]
  },
  {
   "title": "Luminosidade",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._field == \"lux\"\n  )"
    }
   ]
  },
  {
   "title": "Nível Sonoro",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._field == \"noise_db\"\n  )"
    }
   ]
  },
  {
   "title": "Dióxido de Carbono",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._field == \"co2\"\n  )"
    }
   ]
  },
  {
   "title": "VOC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._field == \"voc\"\n  )"
    }
   ]
  },
  {
   "title": "PM25",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._field == \"pm25\"\n  )"
    }
   ]
  },
  {
   "title": "PM10",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"iot\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._field == \"pm10\"\n  )"
    }
   ]
  }
 ]
}